### ISSUE TITLE
Error when child is null.

### ISSUE THREAD

**Issue by windyGex** [developit/preact-transition-group#1]
![image](https://cloud.githubusercontent.com/assets/197348/25168199/2e4bbb5c-2515-11e7-80e8-7ecbd09ecd00.png)

![image](https://cloud.githubusercontent.com/assets/197348/25168818/85446a10-2517-11e7-9517-d2aa01f8763c.png)

![image](https://cloud.githubusercontent.com/assets/197348/25168214/3e103374-2515-11e7-953c-c34343d49035.png)

err @ preact 8.x

code

```js
<TransitionGroup>
    {null}
</TransitionGroup>
```

@developit

**Comment by developit** [comment]
Yup, same issue as the `preact-css-transition-group` error that was fixed here:
developit/preact-css-transition-group#10

**Comment by windyGex** [comment]
But this pkg was not fixed ? Maybe there is no association between the two pkgs ?

**Comment by developit** [comment]
Indeed, they are two different things. I'd be happy to accept a PR, might take me a bit to get around to it otherwise.

**Comment by developit** [comment]
Fixed and released as [1.1.1](https://github.com/developit/preact-transition-group/releases/tag/1.1.1).

**Comment by windyGex** [comment]
Ok, thx.
